# SpringBoot自动注入属性 https://docs.spring.io/spring-boot/docs/1.5.11.BUILD-SNAPSHOT/reference/htmlsingle/#common-application-properties

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource:
  url: jdbc:mysql://localhost:3306/springboot_data_solr_shop?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
  username: root
  password: love.you
  driver-class-name: # Fully qualified name of the JDBC driver. Auto-detected based on the URL by default.

# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

# SOLR (SolrProperties)
spring.data.solr:
  host: http://localhost:8983/solr/springboot_data_solr_shop # Solr host. Ignored if "zk-host" is set.
  repositories.enabled: true # Enable Solr repositories.
  zk-host: # ZooKeeper host address in the form HOST:PORT.